name: Releases

on:
  workflow_dispatch:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*"
          artifactContentType: "raw"
          bodyFile: "body.md"
          draft: false
          prerelease: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
